# Generated by Django 3.1.12 on 2026-04-12 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20260412_1646'),
    ]

    operations = [
    ]
